"""
Django settings for sandbox project.

Generated by 'django-admin startproject' using Django 3.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from typing import Dict

from decouple import config
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# @todo : This is dummy secret key generated randomly. it should be removed on Production!
SECRET_KEY = 't&m_xf9-3oxel_sxfj$8*$l3v(xg@8x-or3v=y7^pxx21yoc7t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["plumar.co", "www.plumar.co", "172.105.47.46", "157.230.178.31", "127.0.0.1", "localhost"]

CSRF_TRUSTED_ORIGINS = [
    'http://157.230.178.31',
    'http://172.105.47.46',
    'http://plumar.co',
    'https://plumar.co',
    'http://66.228.59.219',
]

# Application definition

INSTALLED_APPS = [
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'tinymce',
    'mathfilters',
    # 'social_django',
    "django_crontab",
    # "django_q",
    'django_social_share',
    'hitcount',
    'home',
    'opportunity',
    'startups',
    'dashboard',
    'userauth',
    'talents',
]

X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

# Q_CLUSTER = {
#     "name": "shop",
#     "orm": "default",  # Use Django's ORM + database for broker
#     'timeout': 60,
# }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # whitenoise middleware
    "whitenoise.middleware.WhiteNoiseMiddleware",

    # social loging configs
    # 'social_django.middleware.SocialAuthExceptionMiddleware',
]

RATING_MODEL = "dashboard.Rating"
OPPORTUNITY_MODEL = "opportunity.Opportunity"
MATCHES_MODEL = "dashboard.Matches"

GRAPPELLI_ADMIN_TITLE = "Plumar Administration"

ROOT_URLCONF = 'sandbox.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # 'django.template.context_processors.request',

                # social login configs
                # 'social_django.context_processors.backends',
                # 'social_django.context_processors.login_redirect',
            ],
        },
    },
]

# kpyalvgmziafnckb


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'plumartechnical@gmail.com'
EMAIL_HOST_PASSWORD = 'kpyalvgmziafnckb'
EMAIL_PORT = 587

BEEM_API_KEY = "3a86d4c7fefce676"
BEEM_SECRET_KEY = "MDMxYmI4YTZlNWVhYWRkOGY1Njk2N2UyYmQwYTFhOTM2YTI5NWRkZGE3ZmNlZTYwMGVhOTcyMzA2YmIyMzg3Mg=="

FLUTTER_WAVE_PUBLIC_KEY = 'FLWPUBK-beb8a5a0af5c4343b38e5831d6424963-X'
FLUTTER_WAVE_SECRET_KEY = 'FLWSECK-e64b791b6a400370ff9e5a05f91a65cb-X'
FLUTTER_WAVE_PAYMENTS_URL = 'https://api.flutterwave.com/v3/payments'

CRONJOBS = [
    ("*/30 * * * *", "dashboard.schedulers.zoom_meeting_reminder", '>> /logs/cron_log.log'),  # Every 30 minutes
    ("*/30 * * * *", "opportunity.schedulers.check_expired_opportunity", '>> /logs/cron_log.log'),
    # Every 30 minutes
]

ZOOM_API_PUBLIC_KEY = 'vGo-AjLnS5ynuY5Qiuf3VA'
ZOOM_API_JWT_TOKEN = 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOm51bGwsImlzcyI6InZHby1BakxuUzV5bnVZNVFpdWYzVkEiLCJleHAiOjE5MTc4NTUwMDAsImlhdCI6MTY2MzY5MTIzMX0.gpFL4WnuPgv-w8gWh5xh7hVXOlvvlm4Y2Dr3_S5V8EA'

SITE_CALLBACK_URL = 'https://plumar.co/callback'
FAV_ICON_URL = 'https://plumar/static/assets/img/fav.png'

FROM_EMAIL = 'plumartechnical@gmail.com'

# Twilio SendGrid
# EMAIL_HOST = 'smtp.sendgrid.net'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'shed.dev23@gmail.com'  # Name for all the SenGrid accounts
# EMAIL_HOST_PASSWORD = SENDGRID_API_KEY
# DEFAULT_FROM_EMAIL = FROM_EMAIL

# AUTHENTICATION_BACKENDS = (
#     'social_core.backends.facebook.FacebookOAuth2',
#     'social_core.backends.twitter.TwitterOAuth',
#     # 'social_core.backends.github.GithubOAuth2',
#     'social_core.backends.linkedin.LinkedinOAuth2',

#     'django.contrib.auth.backends.ModelBackend',
# )


# LOGIN_URL = 'login'
# LOGOUT_URL = 'logout'
# LOGIN_REDIRECT_URL = 'home'


# #facebook configs
# SOCIAL_AUTH_FACEBOOK_KEY = '592228875207376'
# SOCIAL_AUTH_FACEBOOK_SECRET = '049c1a21a88fdf2b6af5df4b26c75ad4'

# #twitter login
# SOCIAL_AUTH_TWITTER_KEY = '1XcTXfFBcbQNGwoZkAt0AM13K' 
# SOCIAL_AUTH_TWITTER_SECRET = 'QmK5Eu0rTHc8RoBN2mhoOvjhD2IXbNpjz8l1WANc0D4LqEtKER'


# #linked in login
# SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = '77bb0nbf2u3lr9'         # Client ID
# SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = 'K3kT9MKhfXAlOHAk'


WSGI_APPLICATION = 'sandbox.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


DATABASES: Dict[str, dict] = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": 'plumar',
        "HOST": "localhost",
        "PASSWORD": 'root',
        "USER": 'postgres',
        "PORT": 5432,
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE: str = "Africa/Dar_es_Salaam"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"

MEDIA_URL = "/media/"

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
# EMAIL_FILE_PATH = BASE_DIR / "sent_emails"


TINYMCE_DEFAULT_CONFIG = {
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 20,
    'selector': 'textarea',
    'content_style': '.mce-content-body {font-size:15px;font-family:"Open Sans", sans-serif;}',
    'theme': 'silver',
    "height": 500,
    'plugins': '''
            textcolor save link image media preview codesample contextmenu
            table code lists fullscreen  insertdatetime  nonbreaking
            contextmenu directionality searchreplace wordcount visualblocks
            visualchars code fullscreen autolink lists  charmap print  hr
            anchor pagebreak

            advlist,image,code,paste,
            ''',
    'toolbar1': '''
            fullscreen preview bold italic underline | fontselect,
            fontsizeselect  | forecolor backcolor | alignleft alignright |
            aligncenter alignjustify | indent outdent | bullist numlist table |
            | link image media | codesample |
            ''',
    'toolbar2': '''
            visualblocks visualchars |
            charmap hr pagebreak nonbreaking anchor |  code |
            ''',
    'contextmenu': 'formats | link image',
    'menubar': True,
    'statusbar': True,
}

# Celery settings
CELERY_BROKER_URL = "redis://localhost:6379"
CELERY_RESULT_BACKEND = "redis://localhost:6379"
