# Generated by Django 4.0.4 on 2022-09-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='size',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
