# Generated by Django 4.0.4 on 2022-09-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_alter_startup_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
