# Generated by Django 4.0.4 on 2022-09-22 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0013_quizquestionanswer_quiz_question'),
        ('startups', '0003_startup_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.CharField(max_length=1028)),
                ('default_password', models.BooleanField(default=True)),
                ('duration', models.IntegerField(default=60)),
                ('password', models.CharField(max_length=100, null=True)),
                ('pre_schedule', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('schedule_for', models.EmailField(max_length=254)),
                ('allow_multiple_devices', models.BooleanField(default=True)),
                ('auto_recording', models.CharField(default='cloud', max_length=128)),
                ('contact_name', models.CharField(max_length=1028)),
                ('contact_email', models.EmailField(max_length=254)),
                ('email_notification', models.BooleanField(default=True)),
                ('join_before_host', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=128)),
                ('topic', models.CharField(max_length=1028)),
                ('interviewee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talents.talent')),
                ('interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='startups.startup')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddIndex(
            model_name='zoommeeting',
            index=models.Index(fields=['interviewer', 'interviewee'], name='startups_zo_intervi_c71d56_idx'),
        ),
    ]
