# Generated by Django 4.0.4 on 2022-09-22 00:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_zoommeeting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeeting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 22, 0, 34, 21, 685588, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='encrypted_password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='host_email',
            field=models.EmailField(default='hedrick', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='host_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='join_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='meeting_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='meeting_uuid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='start_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='status',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
