# Generated by Django 4.0.4 on 2022-09-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0005_zoommeeting_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoommeeting',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='contact_name',
            field=models.CharField(max_length=1028, null=True),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='schedule_for',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='topic',
            field=models.CharField(max_length=1028, null=True),
        ),
    ]
