# Generated by Django 4.0.4 on 2022-09-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0006_alter_zoommeeting_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeeting',
            name='interviewee_attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='interviewer_attended',
            field=models.BooleanField(default=False),
        ),
    ]
