# Generated by Django 4.0.4 on 2022-09-22 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_packagepayment_date_paid'),
        ('opportunity', '0001_initial'),
        ('startups', '0007_zoommeeting_interviewee_attended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeeting',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.matches'),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opportunity.opportunity'),
        ),
    ]
