# Generated by Django 4.0.4 on 2022-09-28 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startups', '0010_alter_zoommeeting_opportunity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='startup',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='logo',
            field=models.FileField(null=True, upload_to='startup_images'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='size',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
