# Generated by Django 4.0.4 on 2022-09-28 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startups', '0011_alter_startup_description_alter_startup_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
