# Generated by Django 4.0.4 on 2022-09-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0012_alter_startup_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeeting',
            name='first_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
