# Generated by Django 4.0.4 on 2022-09-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0013_zoommeeting_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeeting',
            name='second_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
