# Generated by Django 4.0.4 on 2022-09-20 09:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talents', '0001_initial'),
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('charge', models.CharField(default=0, max_length=100)),
                ('opportunity_listing', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100)),
                ('talent_due_deligency', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100)),
                ('legal', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100)),
                ('payroll', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100)),
                ('category', models.CharField(choices=[('junior_roles', 'junior_roles'), ('mid_level_roles', 'mid_level_roles'), ('senior_roles', 'senior_roles')], max_length=100, null=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_date', models.DateTimeField(default=datetime.datetime.now)),
                ('rating_value', models.FloatField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('rating_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rating_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talents.talent')),
            ],
        ),
        migrations.CreateModel(
            name='PackagePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_opportunity', models.IntegerField()),
                ('amount_paid', models.CharField(max_length=100)),
                ('txt_ref', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('date_paid', models.DateTimeField(default=datetime.datetime.now)),
                ('package_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_message', models.TextField()),
                ('sent_on', models.DateTimeField(default=datetime.datetime.now)),
                ('thread', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.thread')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_on', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('shortlisted', 'shortlisted'), ('rejected', 'rejected'), ('reviewing', 'reviewing'), ('interviewed', 'interviewed'), ('offergiven', 'offergiven')], default='reviewing', max_length=100)),
                ('opportunity', models.ManyToManyField(to='opportunity.opportunity')),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('talent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talents.talent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
