# Generated by Django 4.0.4 on 2022-09-21 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_packagepayment_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ('-id',)},
        ),
    ]
