# Generated by Django 4.0.4 on 2022-09-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_rating_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagepayment',
            name='active_payment',
            field=models.BooleanField(default=True),
        ),
    ]
