# Generated by Django 4.0.4 on 2022-09-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0010_alter_zoommeeting_opportunity_and_more'),
        ('opportunity', '0003_alter_opportunity_date_published_and_more'),
        ('dashboard', '0006_alter_packagepayment_date_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagepayment',
            name='opportunities',
            field=models.ManyToManyField(to='opportunity.opportunity'),
        ),
        migrations.AddField(
            model_name='packagepayment',
            name='startup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='startups.startup'),
        ),
    ]
