# Generated by Django 4.0.4 on 2022-09-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_packagepayment_opportunities_packagepayment_startup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagepayment',
            name='amount_paid',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='packagepayment',
            name='date_paid',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='packagepayment',
            name='txt_ref',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
