# Generated by Django 4.0.4 on 2022-09-28 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_packagepayment_can_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagepayment',
            name='amount_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packagepayment',
            name='date_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packagepayment',
            name='package_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.package'),
        ),
        migrations.AlterField(
            model_name='packagepayment',
            name='txt_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
