# Generated by Django 4.0.4 on 2022-09-28 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_packagepayment_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagepayment',
            name='posted_opportunity',
        ),
    ]
