# Generated by Django 4.0.4 on 2022-09-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_packagepayment_opportunities_to_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagepayment',
            name='auto_created',
            field=models.BooleanField(default=False),
        ),
    ]
