# Generated by Django 4.1.1 on 2023-05-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_packagepayment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('junior_roles', 'Junior'), ('mid_level_roles', 'Mid Level'), ('senior_roles', 'Senior')], max_length=100, null=True),
        ),
    ]
