# Generated by Django 4.0.4 on 2022-09-20 09:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('full time', 'full time'), ('remote', 'remote'), ('contractual', 'contractual'), ('internship', 'internship'), ('voluntering', 'voluntering'), ('freelance', 'freelance'), ('part-time', 'part-time'), ('temporary', 'temporary'), ('internship', 'internship')], max_length=100)),
                ('salary_range', models.CharField(choices=[('0 - 500k', '0 - 500k'), ('500k - 1M', '500k - 1M'), ('1M - 3M', '1M - 3M'), ('3M - 5M', '3M - 5M'), ('5M - 8M', '5M - 8M'), ('8M and More', '8M and More')], max_length=100)),
                ('experience', models.CharField(default='1', max_length=100)),
                ('logo', models.FileField(blank=True, null=True, upload_to='job_logo')),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('skills_required', tinymce.models.HTMLField(blank=True, null=True)),
                ('duties_and_responsibilities', tinymce.models.HTMLField(blank=True, null=True)),
                ('sector', models.CharField(choices=[('Architecture & Construction', 'Architecture & Construction'), ('Accountancy and Financial Management', 'Accountancy and Financial Management'), ('Business, Consulting and Management', 'Business, Consulting and Management '), ('Law and Legal Services', 'Law and Legal Services'), ('Non Government Organization', 'Non Government Organization '), ('Media and Communications', 'Media and Communications'), ('Creative Arts and Design', 'Creative Arts and Design'), ('Energy and Utilities', 'Energy and Utilities'), ('Engineering and Manufacturing', 'Engineering and Manufacturing'), ('Agribusiness', 'Agribusiness'), ('Medical and Healthcare', 'Medical and Healthcare'), ('Information Technology', 'Information Technology'), ('Hospitality and Tourism', 'Hospitality and Tourism'), ('Marketing, Advertising and PR', 'Marketing, Advertising and PR'), ('Sales', 'Sales'), ('Real Estate', 'Real Estate'), ('Finance, Retail and Banking Services', 'Finance, Retail and Banking Services'), ('Office Management and Human Resources Services', 'Office Management and Human Resources Services'), ('Transportation, Distribution & Logistics', 'Transportation, Distribution & Logistics')], max_length=100)),
                ('date_published', models.DateTimeField(default=datetime.datetime.now)),
                ('deadline', models.DateTimeField(default=datetime.datetime.now)),
                ('matched', models.CharField(default=0, max_length=255)),
                ('marked', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('startup_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='startups.startup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunity.opportunity')),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
