# Generated by Django 4.0.4 on 2022-09-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0002_opportunity_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
