# Generated by Django 4.0.4 on 2022-09-28 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunity', '0004_alter_opportunity_matched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='marked',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='matched',
            field=models.IntegerField(default=0),
        ),
    ]
