# Generated by Django 4.0.4 on 2022-09-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0005_alter_opportunity_marked_alter_opportunity_matched'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
