# Generated by Django 4.0.4 on 2022-09-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=128, null=True)),
                ('location', models.CharField(max_length=128)),
                ('profession', models.CharField(max_length=128)),
                ('engage_as', models.CharField(choices=[('talent', 'Talent'), ('startup', 'Startup'), ('partner', 'Partner'), ('investor', 'Investor')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True)),
                ('search_count', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('-search_count',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('company_name', models.CharField(max_length=128)),
                ('position', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=13)),
                ('description', models.CharField(max_length=128)),
                ('expectations', models.CharField(max_length=128)),
                ('achievement', models.CharField(max_length=128)),
                ('design', models.FileField(upload_to='projects')),
                ('mockup', models.FileField(upload_to='projects')),
                ('delivery_time', models.CharField(max_length=128)),
                ('budget', models.CharField(max_length=128)),
                ('more_info', models.TextField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('career_background', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddIndex(
            model_name='popularsearch',
            index=models.Index(fields=['keyword'], name='home_popula_keyword_da31b3_idx'),
        ),
    ]
