# Generated by Django 4.0.4 on 2022-09-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0003_talentquiz_time_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='show_badge',
            field=models.BooleanField(default=False),
        ),
    ]
