# Generated by Django 4.0.4 on 2022-09-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0004_talent_show_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentquiz',
            name='time_left',
            field=models.FloatField(null=True),
        ),
    ]
