# Generated by Django 4.0.4 on 2022-09-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0005_alter_talentquiz_time_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentquiz',
            name='timed_out',
            field=models.BooleanField(default=False),
        ),
    ]
