# Generated by Django 4.0.4 on 2022-09-21 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0007_alter_quiz_time_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='started_talent_quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='started_talent_quiz', to='talents.talentquiz'),
        ),
    ]
