# Generated by Django 4.0.4 on 2022-09-21 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0008_talent_started_talent_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='started_talent_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_talent_quiz', to='talents.talentquiz'),
        ),
    ]
