# Generated by Django 4.0.4 on 2022-09-21 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0009_alter_talent_started_talent_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentquizanswer',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talents.quizquestionanswer'),
        ),
    ]
