# Generated by Django 4.0.4 on 2022-09-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0013_quizquestionanswer_quiz_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='passing_average',
            field=models.IntegerField(null=True),
        ),
    ]
