# Generated by Django 4.0.4 on 2022-09-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0014_quiz_passing_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
