# Generated by Django 4.0.4 on 2022-09-28 12:20

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0015_alter_talent_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='category',
            field=models.CharField(choices=[('Architecture & Construction', 'Architecture & Construction'), ('Accountancy and Financial Management', 'Accountancy and Financial Management'), ('Business, Consulting and Management', 'Business, Consulting and Management '), ('Law and Legal Services', 'Law and Legal Services'), ('Non Government Organization', 'Non Government Organization '), ('Media and Communications', 'Media and Communications'), ('Creative Arts and Design', 'Creative Arts and Design'), ('Energy and Utilities', 'Energy and Utilities'), ('Engineering and Manufacturing', 'Engineering and Manufacturing'), ('Agribusiness', 'Agribusiness'), ('Medical and Healthcare', 'Medical and Healthcare'), ('Information Technology', 'Information Technology'), ('Hospitality and Tourism', 'Hospitality and Tourism'), ('Marketing, Advertising and PR', 'Marketing, Advertising and PR'), ('Sales', 'Sales'), ('Real Estate', 'Real Estate'), ('Finance, Retail and Banking Services', 'Finance, Retail and Banking Services'), ('Office Management and Human Resources Services', 'Office Management and Human Resources Services'), ('Transportation, Distribution & Logistics', 'Transportation, Distribution & Logistics')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='languages',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='prefered_work_type',
            field=models.CharField(choices=[('full time', 'Full Time'), ('remote', 'Remote'), ('contractual', 'Contractual'), ('internship', 'Internship'), ('voluntering', 'Voluntering'), ('freelance', 'Freelance'), ('part-time', 'Part Time'), ('temporary', 'Temporary'), ('internship', 'Internship')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='profession',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='salary_expectation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='slug',
            field=models.SlugField(default=django.contrib.auth.models.User, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='years_of_experience',
            field=models.CharField(choices=[('Less than 1 Year', 'Less than 1 Year'), ('2-5 years', '2-5 years'), ('5-7 years', '5-7 years'), ('7-10 years', '7-10 years'), ('10 years and above', '10 years and above')], max_length=100, null=True),
        ),
    ]
