# Generated by Django 4.1.1 on 2023-05-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0016_alter_talent_about_alter_talent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('Software Engineers', 'Software Engineers'), ('UI/UX Designers', 'UI/UX Designers'), ('Tech Sales Engineers', 'Tech Sales Engineers '), ('Data Scientists', 'Data Scientists'), ('Product Managers', 'Product Managers'), ('Digital Marketing', 'Digital Marketing')], max_length=128),
        ),
        migrations.AlterField(
            model_name='talent',
            name='category',
            field=models.CharField(choices=[('Software Engineers', 'Software Engineers'), ('UI/UX Designers', 'UI/UX Designers'), ('Tech Sales Engineers', 'Tech Sales Engineers '), ('Data Scientists', 'Data Scientists'), ('Product Managers', 'Product Managers'), ('Digital Marketing', 'Digital Marketing')], max_length=100, null=True),
        ),
    ]
